<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>329c6e05-421c-4d28-881f-02bc9889cc8f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\prescriptions\" />
    <Folder Include="wwwroot\uploads\products\" />
    <Folder Include="wwwroot\uploads\services\" />
  </ItemGroup>

  <ItemGroup>
  	<Content Update="wwwroot/images/**">
  		<CopyToPublishDirectory>Never</CopyToPublishDirectory>
  	</Content>
  	<Content Update="wwwroot/uploads/**">
  		<CopyToPublishDirectory>Never</CopyToPublishDirectory>
  	</Content>
  </ItemGroup>

</Project>
